version: "3.8"

services:
  frontend:
    container_name: barker-user-website-client
    build: ./user-website/client
    ports:
      - "5173:5173"

  backend:
    container_name: barker-user-website-server
    build: ./user-website/server
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - PORT=3000
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672

  mongodb:
    container_name: barker-user-website-database
    image: mongo:6
    ports:
      - "27018:27017"

  rabbitmq:
    container_name: barker-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  moderation-svc:
    container_name: barker-moderation-svc
    build: ./moderation-svc/server
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672

  email-svc:
    container_name: barker-email-service
    build: ./email-svc/
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672

  test-svc:
    container_name: test-svc
    build: ./test-svc/
    environment:
      - BACKEND_URL=http://backend:3000
