version: "3.8"
services:
  # DOCKER RABBITMQ INSTANCE
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # RabbitMQ AMQP port
      - "15672:15672" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # USER APP SERVER
  user-app-server:
    build: ./user-app/server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://host.docker.internal
    depends_on:
      - rabbitmq
    restart: always

  # USER SVC SERVER
  user-svc-server:
    build: ./user-svc/server
    environment:
      - RABBITMQ_URL=amqp://host.docker.internal
    restart: always

  # LOAD TESTING
  load-test-svc-user-signup:
    build: ./load-test-svc/
    depends_on:
      - user-app-server
    restart: always
