apiVersion: apps/v1
kind: Deployment
metadata:
  name: barker-user-app-server
  labels:
    app: barker-user-app-server # Fixed typo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barker-user-app-server # Fixed typo
  template:
    metadata:
      labels:
        app: barker-user-app-server
    spec:
      containers:
        - name: barker-user-app-server
          image: barker-user-app-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: barker-user-app-server
spec:
  selector:
    app: barker-user-app-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
